name: itube
description: A Flutter app to play YouTube videos with deep link support, captions, and fullscreen mode.
publish_to: "none" # This app is not intended for publishing

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  youtube_player_flutter: ^9.1.3
  flutter_inappwebview: ^6.1.5
  app_links: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  rename: ^3.1.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    # App assets
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image.png"
